// Product Data

const products = [
  {
    id: 1,
    name: "OKAZU Lovers Set (230mL/12 jars)",
    price: 135.0,
    oldPrice: 167.88,
    img: "assets/images/products/okazu-img.png",
    category: "Chili oil/Okazu",
    type: "Multi Set",
    stars: 5,
    reviews: 32,
    thumbnail: [
      "assets/images/products/okazu-chilli-img.png",
      "assets/images/products/miso-soup-img.png",
      "assets/images/products/abo-matcha-img.png",
    ],
  },

  {
    id: 2,
    name: "OKAZU – CHILI MISO chili oil condiment (230mL)",
    price: 13.99,
    oldPrice: null,
    img: "assets/images/products/okazu-chilli-img.png",
    category: "Chili oil/Okazu",
    type: "Single Pack",
    stars: 1,
    reviews: 24,
    thumbnail: [
      "assets/images/products/okazu-img.png",
      "assets/images/products/miso-soup-img.png",
      "assets/images/products/abo-matcha-img.png",
    ],
  },

  {
    id: 3,
    name: "Instant Miso Soup Tasting Set",
    price: 19.99,
    oldPrice: 24.0,
    img: "assets/images/products/miso-soup-img.png",
    category: "Miso Soup",
    type: "Multi Set",
    stars: 2,
    reviews: 18,
    thumbnail: [
      "assets/images/products/okazu-img.png",
      "assets/images/products/okazu-chilli-img.png",
      "assets/images/products/abo-matcha-img.png",
    ],
  },

  {
    id: 4,
    name: "ABO Matcha: Uji matcha, Organic",
    price: 34.0,
    oldPrice: null,
    img: "assets/images/products/abo-matcha-img.png",
    category: "Instant Matcha",
    type: "Single Pack",
    stars: 3,
    reviews: 27,
    thumbnail: [
      "assets/images/products/okazu-img.png",
      "assets/images/products/okazu-chilli-img.png",
      "assets/images/products/miso-soup-img.png",
    ],
  },

  {
    id: 5,
    name: "OKAZU Lovers Set (230mL/12 jars)",
    price: 135.0,
    oldPrice: 167.88,
    img: "assets/images/products/okazu-img.png",
    category: "Chili oil/Okazu",
    type: "Multi Set",
    stars: 4,
    reviews: 32,
    thumbnail: [
      "assets/images/products/okazu-chilli-img.png",
      "assets/images/products/miso-soup-img.png",
      "assets/images/products/abo-matcha-img.png",
    ],
  },

  {
    id: 6,
    name: "OKAZU – CHILI MISO chili oil condiment (230mL)",
    price: 13.99,
    oldPrice: null,
    img: "assets/images/products/okazu-chilli-img.png",
    category: "Chili oil/Okazu",
    type: "Single Pack",
    stars: 1,
    reviews: 24,
    thumbnail: [
      "assets/images/products/okazu-img.png",
      "assets/images/products/miso-soup-img.png",
      "assets/images/products/abo-matcha-img.png",
    ],
  },

  {
    id: 7,
    name: "Instant Miso Soup Tasting Set",
    price: 19.99,
    oldPrice: 24.0,
    img: "assets/images/products/miso-soup-img.png",
    category: "Miso Soup",
    type: "Multi Set",
    stars: 2,
    reviews: 18,
    thumbnail: [
      "assets/images/products/okazu-img.png",
      "assets/images/products/okazu-chilli-img.png",
      "assets/images/products/abo-matcha-img.png",
    ],
  },

  {
    id: 8,
    name: "ABO Matcha: Uji matcha, Organic",
    price: 34.0,
    oldPrice: null,
    img: "assets/images/products/abo-matcha-img.png",
    category: "Instant Matcha",
    type: "Single Pack",
    stars: 5,
    reviews: 27,
    thumbnail: [
      "assets/images/products/okazu-img.png",
      "assets/images/products/okazu-chilli-img.png",
      "assets/images/products/miso-soup-img.png",
    ],
  },

  {
    id: 9,
    name: "OKAZU Lovers Set (230mL/12 jars)",
    price: 135.0,
    oldPrice: 167.88,
    img: "assets/images/products/okazu-img.png",
    category: "Chili oil/Okazu",
    type: "Multi Set",
    stars: 3,
    reviews: 32,
    thumbnail: [
      "assets/images/products/okazu-chilli-img.png",
      "assets/images/products/miso-soup-img.png",
      "assets/images/products/abo-matcha-img.png",
    ],
  },

  {
    id: 10,
    name: "OKAZU – CHILI MISO chili oil condiment (230mL)",
    price: 13.99,
    oldPrice: null,
    img: "assets/images/products/okazu-chilli-img.png",
    category: "Chili oil/Okazu",
    type: "Single Pack",
    stars: 4,
    reviews: 24,
    thumbnail: [
      "assets/images/products/okazu-img.png",
      "assets/images/products/miso-soup-img.png",
      "assets/images/products/abo-matcha-img.png",
    ],
  },

  {
    id: 11,
    name: "Instant Miso Soup Tasting Set",
    price: 19.99,
    oldPrice: 24.0,
    img: "assets/images/products/miso-soup-img.png",
    category: "Miso Soup",
    type: "Multi Set",
    stars: 3,
    reviews: 18,
    thumbnail: [
      "assets/images/products/okazu-img.png",
      "assets/images/products/okazu-chilli-img.png",
      "assets/images/products/abo-matcha-img.png",
    ],
  },

  {
    id: 12,
    name: "ABO Matcha: Uji matcha, Organic",
    price: 34.0,
    oldPrice: null,
    img: "assets/images/products/abo-matcha-img.png",
    category: "Instant Matcha",
    type: "Single Pack",
    stars: 5,
    reviews: 27,
    thumbnail: [
      "assets/images/products/okazu-img.png",
      "assets/images/products/okazu-chilli-img.png",
      "assets/images/products/miso-soup-img.png",
    ],
  },
];
